### ISSUE TITLE
Unable to get to work

### ISSUE THREAD

**Issue by JonBoulter** [tbesluau/sampleblock#1]
Hi,

I've used the deploy to heroku button and got a working app on there, but when using the Block Tester the content is not being updated.

I've tried different browsers and getting the same results. Using the default block (https://quill-block.herokuapp.com) works so I'm assuming its not a problem with my system ( but wouldn't rely on that) :(

Is there anything I can do to check what is causing the problem?

Kind Regards

Jon

**Comment by JonBoulter** [comment]
Just in case other people are having problems, mine was solved by using https for the blocktester and the widget URLs

**Comment by alemieux3** [comment]
I'm working locally and in blocktester I can see the UI with http, but it doesn't work. If I put htttps in, I get an error 'locahost unexpectedly closed the connection.' I just downloaded the latest files and the example files do not work. 

I am on a Mac, using Chrome.

**Comment by barcellos-pedro** [comment]
> Just in case other people are having problems, mine was solved by using https for the blocktester and the widget URLs

@JonBoulter that worked for me. Thanks a lot!

Do you know why adding ``https`` solve the problem?
